### ISSUE TITLE
webpack issue?

### ISSUE THREAD

**Issue by jesperlandberg** [baptistebriel/smooth-scrolling#24]
Hi,

I am trying to initialise the plugin but I'm getting a module loader error. I'm kind of new to Webpack, do you know how how to fix this error?

Image: http://puu.sh/o5DAo/6e4651782f.png

**Comment by baptistebriel** [comment]
Hi,

Thanks for pointing this out!

I'm not using webpack, but did you tried looking at [this issue](https://github.com/babel/babel-loader/issues/162#issuecomment-158100018) or [this blog post](http://jamesknelson.com/using-es6-in-the-browser-with-babel-6-and-webpack/) ?
Seems like we have to add a `webpack.config.js` — but I'm not completely sure.

Otherwise, can you try to edit the [`package.json`](https://github.com/baptistebriel/smooth-scrolling/blob/master/package.json#L5) file of the module and replace `"main": "index.js"` with `"main": "smooth-scrolling.js"`; relaunch the build task (using npm scripts, gulp, grunt or whatever you use) and see if you still have the error.

**Comment by jesperlandberg** [comment]
hi,

Yeah I am using babel-presets/.babelrc (which they are recommending in the posts).

I tried doing what you said in the package.json and now I'm getting the following:
http://puu.sh/o5FRH/b1e2090bfa.png

Would be cool to get it working with webpack, if not I will need to jump back to my browserify/gulp setup=)

**Comment by baptistebriel** [comment]
Okay, then I guess we should keep `index.js` as the main entry point.

Did you tried the "configuring babel-loader" section of the [blog post](http://jamesknelson.com/using-es6-in-the-browser-with-babel-6-and-webpack/) ?
I think you specially need a `loaders` key in the `webpack.config.js` along the `.babelrc` file:

``` javascript
loaders: [
  {
    loader: "babel-loader",

    include: [
      path.resolve(__dirname, "src"),
    ],

    test: /\.js?$/,

    query: {
      presets: ['es2015'],
    }
  }
]
```

This is basically what the error is about but maybe you'll need a couple of adjustments to make it work.

Also, do you have a "browserify" key in your project's package.json ? [This is what I have on my projects.](https://github.com/baptistebriel/biggie/blob/master/package.json#L49) Maybe it can help!

**Comment by jesperlandberg** [comment]
Hmm yes, I think I have my webpack.config.js configured similiar. Here is a pic of how my config looks:
http://puu.sh/o5RO7/2c3a06ed28.png

When I google this issue i mostly see the .babelrc and es2015 preset solution which I already have implemented, since I had a similiar issue earlier. Maybe I have to google harder=)

**Comment by baptistebriel** [comment]
I also had a hard time figuring out how to make babel work with my browserify setup when they updated to 6.0.. 😄

Maybe try to copy `index.js` (since you have a babel transform on your `src` folder) and just import directly the file, see if you still have the initial error? In that case I guess my transform presets loader query export thingy is not correctly set up! 😅

**Comment by jesperlandberg** [comment]
I hate when configuring stuff takes longer than the actual work:P

I tried copying the index.js and installed the dependencies (dom-classes, dom-event etc) but getting errors, wasn't these hit by that whole NPM drama last week?

**Comment by baptistebriel** [comment]
Yeah indeed; I use the git repo for now, see [`package.json`](https://github.com/baptistebriel/smooth-scrolling/blob/master/package.json#L9). Add theses lines and just re-run `npm i`

**Comment by jesperlandberg** [comment]
Thanks, got it working now, guess that means the problem lays within my configuration then?:)

**Comment by baptistebriel** [comment]
Not sure, because you're not using it as a module but a single file. That means the module has an issue, so I'm leaving this open until I find a solution.

**Comment by nicodotcomputer** [comment]
The **dom-events** module requires the use of a JSON loader for Webpack otherwise it won't work.

A solution for this :
`npm install --save json-loader`

Then in your webpack config file:
`module: {
    loaders: [
        {
            test: /\.json$/, loader: 'json'
        }
    ]
}`

Works like a charm for me now with Webpack. 🍺

**Comment by jackismissing** [comment]
(oh and smooth-scrolling has to be included in the Babel war-machine for the `extends` to work properly, in your webpack -> babel config : 'include: [
                    path.resolve(__dirname, 'node_modules/smooth-scrolling/index'),
                ],'

**Comment by baptistebriel** [comment]
Wow thanks a lot @jackismissing ! 😄 Can you maybe post a PR or the full `webpack.config.js` file so I can close this issue ?

🍻
