### ISSUE TITLE
Cannot use Smooth without module loader?

### ISSUE THREAD

**Issue by shshaw** [baptistebriel/smooth-scrolling#35]
I typically write in vanilla ES2015 JavaScript without using Browserify or Webpack, and as such I can't seem to load Smooth. Simply including the minified Javascript on the page does not actually attach Smooth to the window, leading to `Uncaught ReferenceError: Smooth is not defined` any time I try to use Smooth.

I assume it's an issue somewhere with either [Line 1](https://github.com/baptistebriel/smooth-scrolling/blob/master/smooth-scrolling.js#L1) or [Line 346](https://github.com/baptistebriel/smooth-scrolling/blob/master/smooth-scrolling.js#L346), but I'm not terribly familiar with the different module systems.

**Comment by baptistebriel** [comment]
Sorry about this! It should now be fixed, see [demos/native-scrollbar](https://github.com/baptistebriel/smooth-scrolling/blob/master/demos/native-scrollbar/index.html)

It's really hard to be sure that your code works everywhere and I'm having lots of issues supporting every module loader, etc. I'm also really looking forward to dropping babel on this project but I enjoy writing ES6 way too much. 😁

Please let me know how it turns out and if you can extends Smooth easily or not.

**Comment by shshaw** [comment]
Ah yes. Working now it seems. The demo doesn't work by default (if you just open index.html from the native-scrollbar folder), but if you move smooth-scrolling.js to that folder then it does.
