### ISSUE TITLE
Section scrolling

### ISSUE THREAD

**Issue by zhuraavl** [baptistebriel/smooth-scrolling#55]
Hi! Im new in js. Tell me please, how to make snap scrolling in your script? It most be easy.

**Comment by baptistebriel** [comment]
Hi @zhuraavl,

If you want to set the value of the scroll, you just have to use the [`scrollTo()`](https://github.com/baptistebriel/smooth-scrolling/blob/master/index.js#L269-L280) built-in function.

```javascript
const smooth = new Smooth(options)
smooth.init()
smooth.scrollTo(300)
```

If you want more control on the easing animation, you could use TweenLite.
For example if you're using a custom scrollbar;

```javascript
TweenLite.to(smooth.vars, 1, { target: 300, ease: Expo.easeInOut })
```

Otherwise you can use the [ScrollToPlugin]();

```javascript
TweenLite.to(window, 2, { scrollTo:400 })
```

That should work! You just have to build a custom logic for your snap needs.
Hope it helps.

**Comment by baptistebriel** [comment]
Feel free to re-open the issue if the `scrollTo` method isn't what you were looking for!
