### ISSUE TITLE
Error: "Cannot read property 'run' of undefined"

### ISSUE THREAD

**Issue by matthew-dean** [baptistebriel/smooth-scrolling#70]
I'm getting an error in this method: 
```js
Smooth.prototype.requestAnimationFrame = function requestAnimationFrame () {

    this.rAF = requestAnimationFrame(this.run);
};
```
Error is `Cannot read property 'run' of undefined` for the `this.run` reference. Any reason `this` would be undefined there?

**Comment by baptistebriel** [comment]
Hi there,

Seems like it's on a different scope! If you `console.log(this)` before the error shows up; what's the reference of `this`? It should be the `Smooth` instance.

You might want to do your work directly in the `run` function of `Smooth`, instead of creating a new function (`requestAnimationFrame`) that will call `this.run`; have a look at the [demos](https://github.com/baptistebriel/smooth-scrolling/blob/master/demos/opacity/custom.js#L20).

Otherwise, just [adding](https://github.com/baptistebriel/smooth-scrolling/blob/master/index.js#L65) your `requestAnimationFrame` function to the `createBound` array should do the trick; it will loop through an array of function names and will bind these functions to the Smooth instance.

Feel free to ask if this wasn't clear enough! ;)

**Comment by apollotheme** [comment]
Dear mate,


We are having summer vacation lasts 6 days from 18/7 to 23/7.
http://www.leotheme.com/blog/609-announce-work-schedule-in-summer-vacation-2017.html
Sorry for inconvenience. We support a little slow, wish you sympathize.
We will fix it for you as soon as possible.

Best regards
Support Team
